### ISSUE TITLE
Decimal значение в amount.value не соответствует спецификации API

### ISSUE THREAD

**Issue by plaguedo** [yoomoney/yookassa-sdk-python#4]
Здравствуйте!

При создании платежа посредством `Payment.create(...)` или `PaymentRequestBuilder` с Amount:
```
"amount": {
    "value": '750000.10',
    "currency": "RUB"
}
```
Или же если `amount.value = Decimal('750000.10')`

SDK преобразовывает значение в `amount.value = Decimal('750000.1')`, т.е. убирает постфиксный ноль после запятой.
И, соответственно, в ответ от ЮКассы приходит 400-ый статус код с описанием ошибки: `Error in the payment amount. Specify the amount in correct format. For example, 100.00`

Странное преобразование происходит, как выяснилось при отладке, тут:

https://github.com/yoomoney/yookassa-sdk-python/blob/16c9a2c319e2983871ce5ed0d56434c3542120e4/src/yookassa/domain/models/amount.py#L24

Возможное решение:
`self.__value = Decimal(value).quantize(Decimal('1.11'), rounding = ROUND_HALF_UP)`

**Comment by ostulov** [comment]
Добрый день!

Отправка суммы платежа без второго значения после разделителя не должна вызывать ошибку.
Пришлите, пожалуйста, подробности Вашей попытки (shopid, id платежа или время отправки запроса) на почту cms@yoomoney.ru, чтобы мы могли посмотреть подробности ошибки в логах.

**Comment by plaguedo** [comment]
Спасибо!
Вводит в заблуждение ответ от API (обращения к которому происходили по тестовому ключу). 
В действительности же ошибка была в превышении лимитов, а не в формате значения.
